export const languageMap: { [key: string]: string } = {
	zh: "Mandarin Chinese", // ISO 639-3 for Mandarin
	es: "Spanish",
	en: "English",
	hi: "Hindi",
	bn: "Bengali",
	pt: "Portuguese",
	ru: "Russian",
	ja: "Japanese",
	de: "German",
	jv: "Javanese",
	ko: "Korean",
	fr: "French",
	te: "Telugu",
	mr: "Marathi",
	tr: "Turkish",
	ta: "Tamil",
	vi: "Vietnamese",
	ur: "Urdu",
	gu: "Gujarati",
	pl: "Polish",
	uk: "Ukrainian",
	it: "Italian",
	yo: "Yoruba",
	th: "Thai",
	ar: "Arabic",
	pa: "Punjabi",
	kn: "Kannada",
	ml: "Malayalam",
	or: "Odia",
};

